import 'bootstrap/dist/css/bootstrap.min.css';
import Link from 'next/link';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
      
      <ul class="navbar-nav bg-light m-5 p-5">
        <li class="nav-item">
          <Link class="nav-link"  href="/">Home</Link>
         </li>
         <hr></hr>
        <li class="nav-item">
        <Link class="nav-link"  href="/data">Data</Link>
        </li><hr></hr>
        <li class="nav-item">
        <Link class="nav-link" href="/data/posts">Posts</Link>
        </li><hr></hr>
       
      </ul>
  
        {children}
        </body>
    </html>
  )
}